language: objective-c
osx_image: xcode10.1
branches:
  only:
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - SIMULATOR_ID=$(xcrun instruments -s | grep -o "iPhone 6S (12.1) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
  - gem install xcpretty -N
  - gem install cocoapods -v '1.5.3'
script:
  - echo $SIMULATOR_ID
  - open -b com.apple.iphonesimulator --args -CurrentDeviceUDID $SIMULATOR_ID
  - set -o pipefail
  - xcodebuild -project Mortar.xcodeproj -scheme "Mortar iOS" -sdk "iphonesimulator12.1"
    -destination "OS=12.1,name=iPhone 6S" ONLY_ACTIVE_ARCH=NO  test | xcpretty -c
  - pod lib lint --quick
